backend:
  name: github
  repo: rxnaij/super-save-slot-blog
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog posts
    label_singular: blog post
    folder: blog
    create: true
    slug: index
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - { name: title, label: Title, widget: string }
      - { name: subtitle, label: Subtitle, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: slug, label: Slug, widget: string }
      - { name: tags, label: Tags, widget: list }
      - { name: coverphoto, label: Cover photo, widget: image }
      - { name: body, label: Body, widget: markdown }